### ISSUE TITLE
Manage metadata subscription on ActivityPub

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/federatedcode#14]
I would like to have a way VulnerableCode and/or PurlDB to discover existing Packages available in the FederatedCode ActivityPub (AP) server(s) and to subscribe and be notified on updates. 
This could include:
- [x] #51
- [x] #47

Just to be clear, there is no feature we want that would support browsing or discovering all packages in AP servers. This would be a search feature and something that some AP serve4rs may implement, but not FederatedCode.

**Comment by keshav-space** [comment]
Completed in https://github.com/aboutcode-org/federatedcode/pull/49, https://github.com/aboutcode-org/federatedcode/pull/50 and https://github.com/aboutcode-org/federatedcode/pull/52

**Comment by keshav-space** [comment]
> * [x] [Function(s) and scripts to discover and retrieve existing Packages existing in the AP server(s). The input is always a PURL or list of PURLs. #51](https://github.com/aboutcode-org/federatedcode/issues/51)

To test this follow the steps here https://github.com/aboutcode-org/federatedcode/issues/51#issuecomment-2549211550

> * [x]  [Function(s) and scripts for VulnerableCode and/or PurlDB to subscribe to Package updates over AP #47](https://github.com/aboutcode-org/federatedcode/issues/47)

To test this follow the steps here https://github.com/aboutcode-org/federatedcode/issues/47#issuecomment-2549376964
