### ISSUE TITLE
Update metadata records based on ActivityPub server push

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/federatedcode#15]
In a decentralized scenario, there are two or more servers cooperating. Here I would like to start building this multiserver architecture. Specifically, we should build an application to run in a second VulnerableCode and/or PurlDB server that can receive updates notifications from the FederatedCode ActivityPub server for a package and then fetch the data from the backing git stores. And use this to update this separate VulnerableCode and/or PurlDB instance, including minimally reconciling conflicts.
This could include:
- [ ] Create the function(s)/services to receive updates notifications from the FederatedCode ActivityPub server in VulnerableCode and/or PurlDB
- [ ] Create script(s) to fetch the backing data from the corresponding FederatedCode backing Git repository and update the local records in VulnerableCode and/or PurlDB, reconciling conflicts as needed

**Comment by keshav-space** [comment]
Completed in: https://github.com/aboutcode-org/federatedcode/pull/52, https://github.com/aboutcode-org/federatedcode/pull/49, https://github.com/aboutcode-org/federatedcode/pull/50 and https://github.com/aboutcode-org/purldb/pull/557

> * [x] [Function(s) and scripts to discover and retrieve existing Packages existing in the AP server(s). The input is always a PURL or list of PURLs. #51](https://github.com/aboutcode-org/federatedcode/issues/51)

To test this follow the steps here https://github.com/aboutcode-org/federatedcode/issues/51#issuecomment-2549211550

> * [x]  [Function(s) and scripts for VulnerableCode and/or PurlDB to subscribe to Package updates over AP #47](https://github.com/aboutcode-org/federatedcode/issues/47)

To test this follow the steps here https://github.com/aboutcode-org/federatedcode/issues/47#issuecomment-2549376964
