### ISSUE TITLE
Add publish and subcribe to ScanCode scan

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/federatedcode#16]
As a practical application of FederatedCode, I would like to have an application such that we can publish a ScanCode scan for a Package to the FederatedCode backing git repo(s)/server(s) and advertise it over FederatedCode pub/sub. Then I should be able to discover this scan querying the ActivityPub server and fetch it from the backing git repo on the receiving end.

This could include:

- [x] #23
- [x] #41
- [x] #42

**Comment by keshav-space** [comment]
> * [x]  [Create script to store and publish a ScanCode.io scan in the FederatedCode Git-based architecture #23](https://github.com/aboutcode-org/federatedcode/issues/23)

To test this follow the steps here https://github.com/aboutcode-org/federatedcode/issues/23#issuecomment-2550734719


> * [x]  [Advertise a pushed ScanCode scan in the FederatedCode ActivityPub server #41](https://github.com/aboutcode-org/federatedcode/issues/41)

To test this follow the steps here https://github.com/aboutcode-org/federatedcode/issues/41#issuecomment-2550705096


> * [x]  [Create script to discover the scan for a package in the FederatedCode sytem and fetch it from the backing git repo(s) #42](https://github.com/aboutcode-org/federatedcode/issues/42)

To test this follow the steps here https://github.com/aboutcode-org/federatedcode/issues/42#issuecomment-2550681010
