### ISSUE TITLE
Commit exported VulnerableCode data to the backing git repository(ies)

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/federatedcode#20]
We want to commit the VCIO data export to the Git repository.
For now we can use PR on GitHub. This can be relaxed later with direct commits.

**Comment by keshav-space** [comment]
The simple way to test this is to follow the steps below after installing VulnerableCode (https://vulnerablecode.readthedocs.io/en/latest/installation.html):

1. Supply these environment variables in the `.env` file: `VULNERABLECODE_EXPORT_REPO_URL`, `VULNERABLECODE_GITHUB_SERVICE_TOKEN`, `VULNERABLECODE_GITHUB_SERVICE_NAME`, `VULNERABLECODE_GITHUB_SERVICE_EMAIL`.
2. Run these commands:
    ```
    python3 manage.py export ../vcio-export
    ```
    ```
    python3 manage.py commit_export ../vcio-export
    ```
3. By now, you should have a pull request in your export repo with the latest changes. Review and merge it as needed.
